name: Pipeline deployment
on:
  push:
    branches:
      - main
env:
  IMAGE: ahagbes/calculator
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Create file
        run: echo "Hello world">file.txt
      - name: Copy files via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "file.txt"
          target: /home/${{secrets.USERNAME}}/